services:
  - type: web
    name: codefest-backend
    env: java
    plan: free
    region: oregon
    buildCommand: ./mvnw -DskipTests package
    startCommand: java -jar target/Codefest_Project-0.0.1-SNAPSHOT.jar
    envVars:
      - key: PORT
        value: 10000
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: SPRING_DATASOURCE_URL
        sync: false
      - key: SPRING_DATASOURCE_USERNAME
        sync: false
      - key: SPRING_DATASOURCE_PASSWORD
        sync: false
      - key: JWT_SECRET_KEY
        sync: false
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: MOMO_SUBSCRIPTION_KEY
        sync: false
      - key: MOMO_API_USER
        sync: false
      - key: MOMO_API_KEY
        sync: false
      - key: MOMO_BASE_URL
        sync: false
      - key: MOMO_TARGET_ENVIRONMENT
        sync: false
      - key: SPRING_MAIL_USERNAME
        sync: false
      - key: SPRING_MAIL_PASSWORD
        sync: false
      - key: PAYSTACK_SECRET_KEY
        sync: false
