spring.application.name=${SPRING_APPLICATION_NAME:CodefestProject}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://ep-purple-surf-ap9wyyon-pooler.c-7.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:neondb_owner}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:npg_OaRA67WGvMdr}

spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
spring.jpa.show-sql=${SPRING_JPA_SHOW_SQL:true}

server.port=${PORT:8080}

security.jwt.secret-key=${JWT_SECRET_KEY:/iChiMayDaBRh8Z/MgChM4hitf519F9KSmauUldvKbDA2gUyg1YUhx4ssKlLTPl3}
# 1h in millisecond
security.jwt.expiration-time=${JWT_EXPIRATION_TIME:3600000}

# Cloudinary
cloudinary.cloud-name=${CLOUDINARY_CLOUD_NAME:dt50fjfhy}
cloudinary.api-key=${CLOUDINARY_API_KEY:738721482968615}
cloudinary.api-secret=${CLOUDINARY_API_SECRET:l-iP7z6kXdP9K_yIVSC58DLWIVg}

momo.subscription-key=${MOMO_SUBSCRIPTION_KEY:39825099a1584989bbf9c65c996781f9}
momo.api-user=${MOMO_API_USER:149671ec-4c07-4714-9ebb-0964a25dc2a6}
momo.api-key=${MOMO_API_KEY:a915fa99056c441a895739cdeec3ed1b}
momo.base-url=${MOMO_BASE_URL:https://sandbox.momodeveloper.mtn.com}
momo.target-environment=${MOMO_TARGET_ENVIRONMENT:sandbox}
momo.mock-mode=${MOMO_MOCK_MODE:true}

# Email
spring.mail.host=${SPRING_MAIL_HOST:smtp.gmail.com}
spring.mail.port=${SPRING_MAIL_PORT:587}
spring.mail.username=${SPRING_MAIL_USERNAME:nkosobusiness@gmail.com}
spring.mail.password=${SPRING_MAIL_PASSWORD:wwph dlww obhr pcyq}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# MFI
mfi.email=${MFI_EMAIL:mfi-partner@email.com}

logging.level.org.springframework.security=${LOGGING_LEVEL_SPRING_SECURITY:DEBUG}
logging.level.org.springframework.web=${LOGGING_LEVEL_SPRING_WEB:DEBUG}

spring.servlet.multipart.max-file-size=${SPRING_SERVLET_MULTIPART_MAX_FILE_SIZE:50MB}
spring.servlet.multipart.max-request-size=${SPRING_SERVLET_MULTIPART_MAX_REQUEST_SIZE:50MB}

paystack.secret-key=${PAYSTACK_SECRET_KEY:sk_test_75a886c3945ec780cef1000d6510be283d190da7}
paystack.base-url=${PAYSTACK_BASE_URL:https://api.paystack.co}

management.endpoints.web.exposure.include=health,info
management.endpoint.health.probes.enabled=true