spring.application.name=CodefestProject
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url= jdbc:postgresql://localhost:5432/exploregh
spring.datasource.username = postgres
spring.datasource.password=louis@2007
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

