spring.application.name=CodefestProject
spring.datasource.driver-class-name=org.postgresql.Driver

spring.datasource.url=jdbc:postgresql://ep-purple-surf-ap9wyyon-pooler.c-7.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_OaRA67WGvMdr

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true