import { Pitch, Bid, Deal, ActivityItem, Investment, User } from '@/types';

export const MOCK_PITCHES: Pitch[] = [
  {
    id: 'p1',
    ownerId: 'u3',
    ownerName: 'Abena Mensah',
    businessName: 'GreenCircle',
    description:
      'We partner with small-scale organic farmers across the Ashanti Region to supply fresh produce to Accra supermarkets and restaurants. Our cooperative model ensures farmers get fair prices while reducing food waste through smart logistics. Funds will be used to purchase a refrigerated truck and build a cold storage facility in Kumasi.',
    shortDescription: 'Making sustainable living accessible for everyone in Ghana.',
    videoUrl: 'https://d23dyxeqlo5psv.cloudfront.net/big_buck_bunny.mp4',
    imageUrl: 'https://images.unsplash.com/photo-1542838132-92c53300491e?w=800&q=80',
    monthlyIncome: 8500,
    amountNeeded: 50000,
    amountRaised: 34000,
    offerType: 'EQUITY',
    offerValue: 7.5,
    location: 'Kumasi, Ashanti',
    industry: 'Sustainability',
    status: 'LIVE',
    foundedYear: 2021,
    revenue: 102000,
    minimumInvestment: 100,
    preMoneyValuation: 270000,
    campaignEndDate: '2024-05-30',
    createdAt: '2024-01-15',
  },
  {
    id: 'p2',
    ownerId: 'u4',
    ownerName: 'Kwame Boateng',
    businessName: 'Accra Brew',
    description:
      'Specialty coffee brand sourcing beans from Ghanaian highland farmers and operating modern cafes in high-traffic neighborhoods. We partner with ethical coffee farms and provide barista training to youth. Funds will be used to open 3 new locations in East Legon, Osu, and Tema.',
    shortDescription: 'Specialty coffee brand on a mission to make high-quality coffee accessible while supporting local farmers.',
    imageUrl: 'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=800&q=80',
    monthlyIncome: 18000,
    amountNeeded: 30000,
    amountRaised: 21600,
    offerType: 'EQUITY',
    offerValue: 7.5,
    location: 'Accra, Greater Accra',
    industry: 'Food & Bev',
    status: 'LIVE',
    foundedYear: 2021,
    revenue: 216000,
    minimumInvestment: 100,
    preMoneyValuation: 270000,
    campaignEndDate: '2024-05-30',
    createdAt: '2024-02-01',
  },
  {
    id: 'p3',
    ownerId: 'u5',
    ownerName: 'Esi Quaye',
    businessName: 'PayEasy',
    description:
      'AI-powered mobile payment and bookkeeping solution built specifically for Ghanaian market traders and kiosk owners. Lets business owners track sales, manage inventory, and send invoices with just a feature phone. Currently serving 1,200 traders in Makola Market.',
    shortDescription: 'AI copilot for market traders and small business owners.',
    imageUrl: 'https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?w=800&q=80',
    monthlyIncome: 6200,
    amountNeeded: 20000,
    amountRaised: 8400,
    offerType: 'REVENUE_SHARE',
    offerValue: 12,
    location: 'Accra, Greater Accra',
    industry: 'Technology',
    status: 'LIVE',
    foundedYear: 2022,
    revenue: 74400,
    minimumInvestment: 50,
    preMoneyValuation: 150000,
    campaignEndDate: '2024-06-15',
    createdAt: '2024-02-10',
  },
  {
    id: 'p4',
    ownerId: 'u6',
    ownerName: 'Samuel Agyei',
    businessName: 'HealthLink',
    description:
      'AI-powered health monitoring wristbands distributed through community health workers in rural Northern Ghana. We provide affordable health tracking for malaria, blood pressure, and blood sugar. Partnered with 3 regional hospitals for telemedicine referrals.',
    shortDescription: 'AI-powered health monitoring for rural Ghanaian communities.',
    imageUrl: 'https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?w=800&q=80',
    monthlyIncome: 5500,
    amountNeeded: 25000,
    amountRaised: 13750,
    offerType: 'FIXED',
    offerValue: 15,
    location: 'Tamale, Northern Region',
    industry: 'Health',
    status: 'LIVE',
    foundedYear: 2023,
    revenue: 66000,
    minimumInvestment: 200,
    preMoneyValuation: 200000,
    campaignEndDate: '2024-07-01',
    createdAt: '2024-02-20',
  },
  {
    id: 'p5',
    ownerId: 'u7',
    ownerName: 'Nana Osei',
    businessName: 'PeakMove Fitness',
    description:
      'Community fitness centers in low-income neighborhoods in Kumasi. We offer affordable gym memberships, personal training, and nutrition counseling. Our mission is to make fitness accessible to everyone regardless of income. Expanding to 2 new locations in Asokwa and Bantama.',
    shortDescription: 'Affordable community fitness centers across Kumasi.',
    imageUrl: 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=800&q=80',
    monthlyIncome: 7800,
    amountNeeded: 15000,
    amountRaised: 7050,
    offerType: 'REVENUE_SHARE',
    offerValue: 10,
    location: 'Kumasi, Ashanti',
    industry: 'Fitness',
    status: 'LIVE',
    foundedYear: 2022,
    revenue: 93600,
    minimumInvestment: 100,
    preMoneyValuation: 120000,
    campaignEndDate: '2024-06-30',
    createdAt: '2024-03-01',
  },
  {
    id: 'p6',
    ownerId: 'u8',
    ownerName: 'Akosua Darko',
    businessName: 'Volta Grains',
    description:
      'Cooperative of smallholder farmers in the Volta Region producing certified organic rice, maize, and soybeans. We aggregate production from 50+ farmers, provide training, and connect them directly to urban supermarkets, cutting out middlemen. Funds needed for processing equipment and packaging.',
    shortDescription: 'Connecting Volta Region farmers directly to urban markets.',
    imageUrl: 'https://images.unsplash.com/photo-1464226184884-fa280b87c399?w=800&q=80',
    monthlyIncome: 12000,
    amountNeeded: 35000,
    amountRaised: 10500,
    offerType: 'EQUITY',
    offerValue: 10,
    location: 'Ho, Volta Region',
    industry: 'Agriculture',
    status: 'LIVE',
    foundedYear: 2020,
    revenue: 144000,
    minimumInvestment: 200,
    preMoneyValuation: 300000,
    campaignEndDate: '2024-07-15',
    createdAt: '2024-03-10',
  },
];

export const MOCK_INVESTMENTS: Investment[] = [
  {
    pitchId: 'p1',
    businessName: 'GreenCircle',
    industry: 'Sustainability',
    imageUrl: MOCK_PITCHES[0].imageUrl,
    amount: 1000,
    currentValue: 1187,
    change: 187,
    changePercent: 18.7,
  },
  {
    pitchId: 'p3',
    businessName: 'PayEasy',
    industry: 'Technology',
    imageUrl: MOCK_PITCHES[2].imageUrl,
    amount: 500,
    currentValue: 564,
    change: 64,
    changePercent: 12.8,
  },
  {
    pitchId: 'p2',
    businessName: 'Accra Brew',
    industry: 'Food & Bev',
    imageUrl: MOCK_PITCHES[1].imageUrl,
    amount: 800,
    currentValue: 865,
    change: 65,
    changePercent: 8.1,
  },
  {
    pitchId: 'p4',
    businessName: 'HealthLink',
    industry: 'Health',
    imageUrl: MOCK_PITCHES[3].imageUrl,
    amount: 500,
    currentValue: 511,
    change: 11,
    changePercent: 2.2,
  },
  {
    pitchId: 'p5',
    businessName: 'PeakMove Fitness',
    industry: 'Fitness',
    imageUrl: MOCK_PITCHES[4].imageUrl,
    amount: 400,
    currentValue: 421,
    change: 21,
    changePercent: 5.3,
  },
];

export const MOCK_ACTIVITY: ActivityItem[] = [
  {
    id: 'a1',
    type: 'investment_completed',
    businessName: 'Accra Brew',
    imageUrl: MOCK_PITCHES[1].imageUrl,
    amount: 500,
    isCredit: false,
    description: 'Investment completed',
    date: 'May 15',
    monthLabel: 'May 2024',
  },
  {
    id: 'a2',
    type: 'business_update',
    businessName: 'GreenCircle',
    imageUrl: MOCK_PITCHES[0].imageUrl,
    description: 'GreenCircle opened their new fulfillment center in Kumasi! This expansion will help reduce shipping times by 30%.',
    date: 'May 12',
  },
  {
    id: 'a3',
    type: 'dividend_received',
    businessName: 'PayEasy',
    imageUrl: MOCK_PITCHES[2].imageUrl,
    amount: 120,
    isCredit: true,
    description: 'Dividend received',
    date: 'May 10',
  },
  {
    id: 'a4',
    type: 'investment_completed',
    businessName: 'HealthLink',
    imageUrl: MOCK_PITCHES[3].imageUrl,
    amount: 250,
    isCredit: false,
    description: 'Investment completed',
    date: 'May 2',
  },
  {
    id: 'a5',
    type: 'business_update',
    businessName: 'HealthLink',
    imageUrl: MOCK_PITCHES[3].imageUrl,
    description: 'HealthLink posted an update about their Q1 2024 results.',
    date: 'Apr 28',
    monthLabel: 'April 2024',
  },
  {
    id: 'a6',
    type: 'dividend_received',
    businessName: 'GreenCircle',
    imageUrl: MOCK_PITCHES[0].imageUrl,
    amount: 90,
    isCredit: true,
    description: 'Dividend received',
    date: 'Apr 20',
  },
  {
    id: 'a7',
    type: 'investment_completed',
    businessName: 'GreenCircle',
    imageUrl: MOCK_PITCHES[0].imageUrl,
    amount: 1000,
    isCredit: false,
    description: 'Investment completed',
    date: 'Apr 15',
  },
];

export const MOCK_BIDS: Bid[] = [
  {
    id: 'b1',
    pitchId: 'p1',
    investorId: 'u1',
    investorName: 'Alex Smith',
    amount: 5000,
    returnType: 'EQUITY',
    returnValue: 2.5,
    timelineMonths: 24,
    status: 'PENDING',
    note: 'I love the sustainable farming model and see great growth potential in the Ashanti Region.',
    createdAt: '2024-03-15',
  },
  {
    id: 'b2',
    pitchId: 'p1',
    investorId: 'u2',
    investorName: 'Diana Owusu',
    amount: 3000,
    returnType: 'EQUITY',
    returnValue: 1.5,
    timelineMonths: 18,
    status: 'COUNTERED',
    note: 'Interested in the cold chain logistics aspect.',
    createdAt: '2024-03-16',
  },
  {
    id: 'b3',
    pitchId: 'p2',
    investorId: 'u1',
    investorName: 'Alex Smith',
    amount: 2000,
    returnType: 'REVENUE_SHARE',
    returnValue: 8,
    timelineMonths: 12,
    status: 'ACCEPTED',
    createdAt: '2024-03-10',
  },
];

export const MOCK_DEALS: Deal[] = [
  {
    id: 'd1',
    pitchId: 'p2',
    bidId: 'b3',
    businessName: 'Accra Brew',
    ownerSigned: true,
    investorSigned: false,
    mfiApproved: false,
    repaymentSchedule: [
      { id: 'r1', dealId: 'd1', dueDate: '2024-04-18', amount: 180, status: 'COLLECTED', collectedAt: '2024-04-17' },
      { id: 'r2', dealId: 'd1', dueDate: '2024-05-18', amount: 180, status: 'PENDING' },
      { id: 'r3', dealId: 'd1', dueDate: '2024-06-18', amount: 180, status: 'PENDING' },
    ],
    status: 'PENDING_MFI',
    amount: 2000,
    returnType: 'REVENUE_SHARE',
    returnValue: 8,
    timelineMonths: 12,
    createdAt: '2024-03-18',
  },
];

export const MOCK_INVESTOR: User = {
  id: 'u1',
  name: 'Alex Smith',
  email: 'alex.smith@email.com',
  role: 'INVESTOR',
  isVerified: true,
  ghanaCardVerified: true,
  momoVerified: true,
  momoNumber: '024-XXX-XXXX',
  ghanaCardNumber: 'GHA-XXXXXXXX-X',
};

export const MOCK_OWNER: User = {
  id: 'u3',
  name: 'Abena Mensah',
  email: 'abena.mensah@email.com',
  role: 'OWNER',
  isVerified: true,
  ghanaCardVerified: true,
  momoVerified: true,
  momoNumber: '055-XXX-XXXX',
  ghanaCardNumber: 'GHA-XXXXXXXX-X',
};

export const CHART_DATA = [
  20000, 21500, 20800, 22000, 21200, 23000, 22500, 24000, 23500, 24580,
];
